import type { DfmRule, ManufacturingProcess } from "./types";

export const DFM_RULES: DfmRule[] = [
  // ==========================================
  // SHEET METAL RULES (15 rules)
  // ==========================================

  {
    id: "SM-001",
    name: "Minimum Bend Radius",
    process: "sheet_metal",
    category: "Bending",
    description: "Internal bend radius must be at least equal to material thickness",
    requirement: ">= 1x material thickness",
    threshold: { min: 1, recommended: 1.5 },
    unit: "x thickness",
    severity: "critical",
    reasoning: "Insufficient bend radius causes cracking and material failure",
    fixSuggestion: "Increase bend radius to at least 1x material thickness, 1.5x for aluminum",
  },
  {
    id: "SM-002",
    name: "Hole-to-Edge Distance",
    process: "sheet_metal",
    category: "Holes",
    description: "Distance from hole edge to part edge",
    requirement: ">= 2x material thickness",
    threshold: { min: 2 },
    unit: "x thickness",
    severity: "critical",
    reasoning: "Holes too close to edges cause tearing and deformation",
    fixSuggestion: "Move hole away from edge or add relief notch",
  },
  {
    id: "SM-003",
    name: "Hole-to-Bend Distance",
    process: "sheet_metal",
    category: "Holes",
    description: "Distance from hole center to bend line",
    requirement: ">= 3x material thickness + bend radius",
    threshold: { min: 3 },
    unit: "x thickness + R",
    severity: "critical",
    reasoning: "Holes near bends deform during forming",
    fixSuggestion: "Relocate hole away from bend or add relief slot",
  },
  {
    id: "SM-004",
    name: "Bend Relief",
    process: "sheet_metal",
    category: "Bending",
    description: "Relief cuts at corners where bends meet edges",
    requirement: "Width >= material thickness, Length >= bend radius",
    threshold: { min: 1 },
    unit: "x thickness",
    severity: "critical",
    reasoning: "Missing bend reliefs cause tearing and uncontrolled deformation",
    fixSuggestion: "Add bend relief cut at corner intersections",
  },
  {
    id: "SM-005",
    name: "Minimum Hole Diameter",
    process: "sheet_metal",
    category: "Holes",
    description: "Smallest allowable hole diameter",
    requirement: ">= material thickness",
    threshold: { min: 1 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Small holes increase punch wear and may not punch cleanly",
    fixSuggestion: "Increase hole diameter or use laser cutting",
  },
  {
    id: "SM-006",
    name: "Hole-to-Hole Spacing",
    process: "sheet_metal",
    category: "Holes",
    description: "Minimum distance between adjacent holes",
    requirement: ">= 2x material thickness",
    threshold: { min: 2 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Closely spaced holes weaken material and cause punching issues",
    fixSuggestion: "Increase spacing or combine into oblong slot",
  },
  {
    id: "SM-007",
    name: "Flange Height",
    process: "sheet_metal",
    category: "Bending",
    description: "Minimum flange height for bending",
    requirement: ">= 4x material thickness",
    threshold: { min: 4, recommended: 6 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Short flanges cannot be gripped by brake tooling",
    fixSuggestion: "Extend flange height or consider hem edge",
  },
  {
    id: "SM-008",
    name: "Bend-to-Bend Distance",
    process: "sheet_metal",
    category: "Bending",
    description: "Minimum distance between parallel bends",
    requirement: ">= 6x material thickness",
    threshold: { min: 6, recommended: 8 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Close parallel bends cause interference with tooling",
    fixSuggestion: "Increase spacing or consider single compound bend",
  },
  {
    id: "SM-009",
    name: "Maximum Aspect Ratio",
    process: "sheet_metal",
    category: "Geometry",
    description: "Length-to-width ratio of narrow features",
    requirement: "<= 10:1",
    threshold: { max: 10 },
    unit: "ratio",
    severity: "warning",
    reasoning: "High aspect ratio features warp and twist during handling",
    fixSuggestion: "Add stiffening ribs or reduce aspect ratio",
  },
  {
    id: "SM-010",
    name: "Tab Width",
    process: "sheet_metal",
    category: "Features",
    description: "Minimum width for tabs and projections",
    requirement: ">= 2x material thickness",
    threshold: { min: 2 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Narrow tabs bend or break during handling",
    fixSuggestion: "Widen tab or use different joining method",
  },
  {
    id: "SM-011",
    name: "Emboss Depth",
    process: "sheet_metal",
    category: "Features",
    description: "Maximum emboss/form depth",
    requirement: "<= 3x material thickness",
    threshold: { max: 3, recommended: 2 },
    unit: "x thickness",
    severity: "info",
    reasoning: "Deep embosses thin material excessively",
    fixSuggestion: "Reduce depth or use stamped insert",
  },
  {
    id: "SM-012",
    name: "Grain Direction",
    process: "sheet_metal",
    category: "Bending",
    description: "Bend orientation relative to grain",
    requirement: "Bend perpendicular to grain when possible",
    threshold: {},
    unit: "orientation",
    severity: "info",
    reasoning: "Bending with grain increases cracking risk",
    fixSuggestion: "Rotate part to bend across grain, or increase bend radius",
  },
  {
    id: "SM-013",
    name: "Countersink Depth",
    process: "sheet_metal",
    category: "Holes",
    description: "Countersink must not penetrate through material",
    requirement: "Depth < 60% of material thickness",
    threshold: { max: 0.6 },
    unit: "x thickness",
    severity: "critical",
    reasoning: "Full penetration countersinks weaken fastener connection",
    fixSuggestion: "Reduce countersink depth or use thicker material",
  },
  {
    id: "SM-014",
    name: "Lance Height",
    process: "sheet_metal",
    category: "Features",
    description: "Maximum height of lanced louvers or forms",
    requirement: "<= 4x material thickness",
    threshold: { max: 4 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Excessive lance height causes tearing",
    fixSuggestion: "Reduce height or use two-stage forming",
  },
  {
    id: "SM-015",
    name: "Notch Corner Radius",
    process: "sheet_metal",
    category: "Features",
    description: "Internal corners of notches require radius",
    requirement: ">= 0.5x material thickness",
    threshold: { min: 0.5, recommended: 1 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Sharp internal corners create stress concentrations",
    fixSuggestion: "Add fillet radius to internal corners",
  },

  // CUTOUT & SLOT RULES (Sheet Metal)
  {
    id: "SM-016",
    name: "Cutout Corner Radius",
    process: "sheet_metal",
    category: "Cutouts",
    description: "Internal cutout corners require minimum radius",
    requirement: ">= 0.5x material thickness (laser), >= 1x (punch)",
    threshold: { min: 0.5, recommended: 1 },
    unit: "x thickness",
    severity: "critical",
    reasoning: "Sharp corners in cutouts create stress risers and may not be achievable with punch tooling",
    fixSuggestion: "Add corner radius or use laser cutting for sharp corners",
  },
  {
    id: "SM-017",
    name: "Cutout-to-Edge Distance",
    process: "sheet_metal",
    category: "Cutouts",
    description: "Distance from cutout edge to part edge",
    requirement: ">= 2x material thickness",
    threshold: { min: 2, recommended: 3 },
    unit: "x thickness",
    severity: "critical",
    reasoning: "Cutouts too close to edges cause distortion and may tear during handling",
    fixSuggestion: "Move cutout away from edge or redesign part boundary",
  },
  {
    id: "SM-018",
    name: "Cutout-to-Bend Distance",
    process: "sheet_metal",
    category: "Cutouts",
    description: "Distance from cutout to bend line",
    requirement: ">= 3x material thickness + bend radius",
    threshold: { min: 3 },
    unit: "x thickness + R",
    severity: "critical",
    reasoning: "Cutouts near bends deform unpredictably during forming",
    fixSuggestion: "Relocate cutout or add relief cuts",
  },
  {
    id: "SM-019",
    name: "Minimum Slot Width",
    process: "sheet_metal",
    category: "Slots",
    description: "Minimum width for punched or laser-cut slots",
    requirement: ">= 1x material thickness (laser), >= 1.5x (punch)",
    threshold: { min: 1, recommended: 1.5 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Narrow slots may not punch cleanly and accumulate debris",
    fixSuggestion: "Widen slot or use laser cutting for narrow features",
  },
  {
    id: "SM-020",
    name: "Slot Length-to-Width Ratio",
    process: "sheet_metal",
    category: "Slots",
    description: "Maximum aspect ratio for slots",
    requirement: "<= 5:1 for punching, <= 10:1 for laser",
    threshold: { max: 5, recommended: 3 },
    unit: "ratio",
    severity: "warning",
    reasoning: "Long narrow slots may not punch in one hit and cause tool wear",
    fixSuggestion: "Reduce length or use laser cutting",
  },
  {
    id: "SM-021",
    name: "Slot-to-Edge Distance",
    process: "sheet_metal",
    category: "Slots",
    description: "Minimum distance from slot end to part edge",
    requirement: ">= 2x material thickness",
    threshold: { min: 2 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Slots too close to edges weaken the material",
    fixSuggestion: "Move slot away from edge",
  },
  {
    id: "SM-022",
    name: "Slot-to-Slot Spacing",
    process: "sheet_metal",
    category: "Slots",
    description: "Minimum distance between adjacent slots",
    requirement: ">= 2x material thickness",
    threshold: { min: 2 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Closely spaced slots weaken material between them",
    fixSuggestion: "Increase spacing or combine into single larger opening",
  },
  {
    id: "SM-023",
    name: "Fillet Minimum Radius",
    process: "sheet_metal",
    category: "Fillets",
    description: "Minimum internal fillet radius at corners",
    requirement: ">= 0.5x material thickness",
    threshold: { min: 0.5 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Small fillets create stress concentrations and are hard to form consistently",
    fixSuggestion: "Increase fillet radius",
  },

  // ==========================================
  // CNC MACHINING RULES (15 rules)
  // ==========================================

  {
    id: "CNC-001",
    name: "Internal Corner Radius",
    process: "cnc_machining",
    category: "Features",
    description: "Internal corners must accommodate tool radius",
    requirement: ">= tool radius (typically >= 3mm)",
    threshold: { min: 3, recommended: 6 },
    unit: "mm",
    severity: "critical",
    reasoning: "Sharp internal corners impossible to machine with rotating tools",
    fixSuggestion: "Add fillet radius >= 1/3 of pocket depth",
  },
  {
    id: "CNC-002",
    name: "Deep Pocket Ratio",
    process: "cnc_machining",
    category: "Pockets",
    description: "Maximum depth relative to smallest width dimension",
    requirement: "Depth <= 4x width",
    threshold: { max: 4, recommended: 3 },
    unit: "ratio",
    severity: "critical",
    reasoning: "Deep narrow pockets cause tool deflection and chatter",
    fixSuggestion: "Widen pocket opening or reduce depth",
  },
  {
    id: "CNC-003",
    name: "Minimum Wall Thickness",
    process: "cnc_machining",
    category: "Walls",
    description: "Thin walls vibrate and deform during machining",
    requirement: ">= 1.5mm for metals, >= 2mm for plastics",
    threshold: { min: 1.5, recommended: 2 },
    unit: "mm",
    severity: "critical",
    reasoning: "Thin walls deflect under cutting forces",
    fixSuggestion: "Increase wall thickness or add ribs for support",
  },
  {
    id: "CNC-004",
    name: "Thread Depth",
    process: "cnc_machining",
    category: "Threads",
    description: "Maximum thread engagement depth",
    requirement: "<= 3x thread diameter",
    threshold: { max: 3, recommended: 2.5 },
    unit: "x diameter",
    severity: "warning",
    reasoning: "Deep threads risk tap breakage and poor thread quality",
    fixSuggestion: "Reduce thread depth or use thread insert",
  },
  {
    id: "CNC-005",
    name: "Hole Depth Ratio",
    process: "cnc_machining",
    category: "Holes",
    description: "Maximum hole depth for standard drills",
    requirement: "Depth <= 10x diameter",
    threshold: { max: 10, recommended: 5 },
    unit: "ratio",
    severity: "warning",
    reasoning: "Deep holes cause drill wander and chip evacuation issues",
    fixSuggestion: "Use peck drilling cycle or gun drill for deep holes",
  },
  {
    id: "CNC-006",
    name: "Surface Finish",
    process: "cnc_machining",
    category: "Finish",
    description: "Requested surface finish must be achievable",
    requirement: "Ra >= 0.8um without secondary operations",
    threshold: { min: 0.8, recommended: 1.6 },
    unit: "um Ra",
    severity: "info",
    reasoning: "Very fine finishes require grinding or polishing",
    fixSuggestion: "Specify Ra 1.6um or finer only where functionally needed",
  },
  {
    id: "CNC-007",
    name: "Undercut Access",
    process: "cnc_machining",
    category: "Features",
    description: "Undercuts require special tooling",
    requirement: "Avoid undercuts or design for T-slot cutter access",
    threshold: {},
    unit: "boolean",
    severity: "warning",
    reasoning: "Undercuts need expensive special tooling or EDM",
    fixSuggestion: "Redesign to eliminate undercut or split into multiple parts",
  },
  {
    id: "CNC-008",
    name: "Minimum Hole Diameter",
    process: "cnc_machining",
    category: "Holes",
    description: "Smallest practical drilled hole",
    requirement: ">= 1mm diameter",
    threshold: { min: 1, recommended: 2 },
    unit: "mm",
    severity: "warning",
    reasoning: "Small drills break easily and require slow feeds",
    fixSuggestion: "Increase hole diameter or use EDM for very small holes",
  },
  {
    id: "CNC-009",
    name: "Text/Engraving Size",
    process: "cnc_machining",
    category: "Features",
    description: "Minimum text/engraving line width",
    requirement: ">= 0.5mm line width, >= 3mm character height",
    threshold: { min: 0.5 },
    unit: "mm",
    severity: "info",
    reasoning: "Fine text requires small tools and slow machining",
    fixSuggestion: "Use larger font size or consider laser marking",
  },
  {
    id: "CNC-010",
    name: "Edge Chamfer",
    process: "cnc_machining",
    category: "Edges",
    description: "External edges should have chamfers or breaks",
    requirement: "Add 0.5mm x 45 deg chamfer or 0.3mm break",
    threshold: { min: 0.3, recommended: 0.5 },
    unit: "mm",
    severity: "info",
    reasoning: "Sharp edges are dangerous and prone to burrs",
    fixSuggestion: "Add chamfer callout or edge break note",
  },
  {
    id: "CNC-011",
    name: "Boss Height Ratio",
    process: "cnc_machining",
    category: "Features",
    description: "Tall thin bosses are difficult to machine",
    requirement: "Height <= 4x diameter",
    threshold: { max: 4 },
    unit: "ratio",
    severity: "warning",
    reasoning: "Tall bosses deflect during machining",
    fixSuggestion: "Reduce height, increase diameter, or add supporting ribs",
  },
  {
    id: "CNC-012",
    name: "Flat Bottom Holes",
    process: "cnc_machining",
    category: "Holes",
    description: "Flat bottom holes require end mill",
    requirement: "Specify only where functionally required",
    threshold: {},
    unit: "boolean",
    severity: "info",
    reasoning: "Flat bottoms need end mill instead of faster drill",
    fixSuggestion: "Use standard drill point (118/135 deg) where possible",
  },
  {
    id: "CNC-013",
    name: "T-Slot Access",
    process: "cnc_machining",
    category: "Features",
    description: "T-slots and dovetails need tool access",
    requirement: "Entry slot width >= cutter diameter",
    threshold: {},
    unit: "mm",
    severity: "critical",
    reasoning: "Cutter must physically enter the slot",
    fixSuggestion: "Ensure adequate entry clearance for T-slot cutter",
  },
  {
    id: "CNC-014",
    name: "Corner Radius to Depth",
    process: "cnc_machining",
    category: "Pockets",
    description: "Internal fillet radius relative to pocket depth",
    requirement: "Radius >= 1/3 of pocket depth",
    threshold: { min: 0.33 },
    unit: "ratio",
    severity: "warning",
    reasoning: "Small radius at depth requires small, weak tools",
    fixSuggestion: "Increase corner radius or reduce pocket depth",
  },
  {
    id: "CNC-015",
    name: "Datum Surface",
    process: "cnc_machining",
    category: "Setup",
    description: "Parts need flat datum surfaces for workholding",
    requirement: "At least one flat surface >= 25mm x 25mm",
    threshold: { min: 25 },
    unit: "mm",
    severity: "info",
    reasoning: "Irregular shapes are difficult to clamp securely",
    fixSuggestion: "Add machining datums or soft jaw pockets in design",
  },

  // ==========================================
  // INJECTION MOLDING RULES (15 rules)
  // ==========================================

  {
    id: "IM-001",
    name: "Draft Angle",
    process: "injection_molding",
    category: "Ejection",
    description: "Walls must have draft for mold release",
    requirement: ">= 1 deg per side (2 deg for textured)",
    threshold: { min: 1, recommended: 2 },
    unit: "degrees",
    severity: "critical",
    reasoning: "Parts without draft stick in mold and cause damage",
    fixSuggestion: "Add minimum 1 deg draft to all vertical surfaces",
  },
  {
    id: "IM-002",
    name: "Uniform Wall Thickness",
    process: "injection_molding",
    category: "Walls",
    description: "Wall thickness should be consistent throughout",
    requirement: "Variation <= 25% of nominal thickness",
    threshold: { max: 0.25 },
    unit: "ratio",
    severity: "critical",
    reasoning: "Varying thickness causes sink marks, warpage, and voids",
    fixSuggestion: "Core out thick sections, use ribs instead of solid",
  },
  {
    id: "IM-003",
    name: "Minimum Wall Thickness",
    process: "injection_molding",
    category: "Walls",
    description: "Walls must be thick enough for flow",
    requirement: ">= 0.8mm (ABS), >= 1mm (PP), >= 1.2mm (PC)",
    threshold: { min: 0.8, recommended: 1.5 },
    unit: "mm",
    severity: "critical",
    reasoning: "Thin walls may not fill completely (short shots)",
    fixSuggestion: "Increase wall thickness or adjust gate location",
  },
  {
    id: "IM-004",
    name: "Rib Thickness",
    process: "injection_molding",
    category: "Ribs",
    description: "Rib base thickness relative to wall",
    requirement: "50-70% of wall thickness",
    threshold: { min: 0.5, max: 0.7 },
    unit: "x wall",
    severity: "warning",
    reasoning: "Thick ribs cause sink marks on opposite face",
    fixSuggestion: "Reduce rib thickness to 60% of wall",
  },
  {
    id: "IM-005",
    name: "Rib Height",
    process: "injection_molding",
    category: "Ribs",
    description: "Maximum rib height relative to thickness",
    requirement: "<= 3x rib thickness",
    threshold: { max: 3 },
    unit: "x thickness",
    severity: "warning",
    reasoning: "Tall thin ribs are difficult to fill and eject",
    fixSuggestion: "Add multiple shorter ribs instead of one tall rib",
  },
  {
    id: "IM-006",
    name: "Boss Outer Diameter",
    process: "injection_molding",
    category: "Bosses",
    description: "Boss OD should be limited to prevent sink",
    requirement: "OD <= 2.5x hole ID",
    threshold: { max: 2.5 },
    unit: "x ID",
    severity: "warning",
    reasoning: "Large bosses cause sink marks",
    fixSuggestion: "Reduce boss OD or add gussets instead of solid boss",
  },
  {
    id: "IM-007",
    name: "Corner Radii",
    process: "injection_molding",
    category: "Geometry",
    description: "Internal corners need fillet radius",
    requirement: ">= 0.5x wall thickness",
    threshold: { min: 0.5, recommended: 0.75 },
    unit: "x wall",
    severity: "warning",
    reasoning: "Sharp corners cause stress concentration and flow issues",
    fixSuggestion: "Add fillet radius = 50-75% of wall thickness",
  },
  {
    id: "IM-008",
    name: "Undercuts",
    process: "injection_molding",
    category: "Mold",
    description: "Undercuts require side actions or lifters",
    requirement: "Minimize undercuts for simple 2-part mold",
    threshold: {},
    unit: "boolean",
    severity: "critical",
    reasoning: "Undercuts significantly increase mold cost and cycle time",
    fixSuggestion: "Redesign to eliminate undercut or use snap-fit alternatives",
  },
  {
    id: "IM-009",
    name: "Gate Location",
    process: "injection_molding",
    category: "Mold",
    description: "Gate should be at thickest section",
    requirement: "Gate at thickest wall, flow to thin sections",
    threshold: {},
    unit: "location",
    severity: "info",
    reasoning: "Proper gate placement ensures complete fill",
    fixSuggestion: "Position gate vestiges in non-cosmetic areas",
  },
  {
    id: "IM-010",
    name: "Shut-off Angle",
    process: "injection_molding",
    category: "Mold",
    description: "Mold shut-off surfaces need draft",
    requirement: ">= 3 deg for steel-safe shut-offs",
    threshold: { min: 3 },
    unit: "degrees",
    severity: "warning",
    reasoning: "Shallow shut-offs wear quickly and flash",
    fixSuggestion: "Increase shut-off angle or use witness line",
  },
  {
    id: "IM-011",
    name: "Text Depth",
    process: "injection_molding",
    category: "Features",
    description: "Molded-in text depth",
    requirement: "0.25-0.5mm depth",
    threshold: { min: 0.25, max: 0.5 },
    unit: "mm",
    severity: "info",
    reasoning: "Shallow text is hard to read, deep text is hard to eject",
    fixSuggestion: "Use raised (proud) text on ejector side when possible",
  },
  {
    id: "IM-012",
    name: "Living Hinge",
    process: "injection_molding",
    category: "Features",
    description: "Living hinge web thickness (PP only)",
    requirement: "0.25-0.5mm for polypropylene",
    threshold: { min: 0.25, max: 0.5 },
    unit: "mm",
    severity: "critical",
    reasoning: "Wrong thickness causes hinge failure",
    fixSuggestion: "Use 0.3mm thickness, orient flow perpendicular to hinge",
  },
  {
    id: "IM-013",
    name: "Snap-Fit Deflection",
    process: "injection_molding",
    category: "Features",
    description: "Maximum deflection during assembly",
    requirement: "<= 5% strain for unfilled materials",
    threshold: { max: 5 },
    unit: "% strain",
    severity: "warning",
    reasoning: "Over-deflection causes stress whitening or cracking",
    fixSuggestion: "Increase snap arm length or reduce hook depth",
  },
  {
    id: "IM-014",
    name: "Ejector Pin Location",
    process: "injection_molding",
    category: "Ejection",
    description: "Ejector pins leave witness marks",
    requirement: "Place on non-cosmetic surfaces",
    threshold: {},
    unit: "location",
    severity: "info",
    reasoning: "Ejector marks are visible on surface",
    fixSuggestion: "Add ejector pad or move to hidden surface",
  },
  {
    id: "IM-015",
    name: "Parting Line",
    process: "injection_molding",
    category: "Mold",
    description: "Parting line location affects cosmetics",
    requirement: "Parting line on edges, not cosmetic faces",
    threshold: {},
    unit: "location",
    severity: "info",
    reasoning: "Parting line flash is visible on smooth surfaces",
    fixSuggestion: "Design parting line along sharp edges or steps",
  },

  // ==========================================
  // DIE CASTING RULES (12 rules)
  // ==========================================

  {
    id: "DC-001",
    name: "Draft Angle",
    process: "die_casting",
    category: "Ejection",
    description: "Minimum draft for die casting",
    requirement: ">= 1 deg external, >= 2 deg internal",
    threshold: { min: 1, recommended: 2 },
    unit: "degrees",
    severity: "critical",
    reasoning: "Die casting requires more draft than injection molding",
    fixSuggestion: "Add 2 deg draft minimum to all surfaces",
  },
  {
    id: "DC-002",
    name: "Wall Thickness",
    process: "die_casting",
    category: "Walls",
    description: "Minimum and maximum wall thickness",
    requirement: "1.5mm min, 6mm max recommended",
    threshold: { min: 1.5, max: 6 },
    unit: "mm",
    severity: "critical",
    reasoning: "Thin walls may not fill, thick walls have porosity",
    fixSuggestion: "Core out thick sections, maintain uniform 2-4mm walls",
  },
  {
    id: "DC-003",
    name: "Fillet Radii",
    process: "die_casting",
    category: "Geometry",
    description: "Internal corners need generous fillets",
    requirement: ">= 1mm, preferably >= 2mm",
    threshold: { min: 1, recommended: 2 },
    unit: "mm",
    severity: "warning",
    reasoning: "Sharp corners cause die erosion and stress cracks",
    fixSuggestion: "Add minimum 1.5mm fillet to all internal corners",
  },
  {
    id: "DC-004",
    name: "Rib Thickness",
    process: "die_casting",
    category: "Ribs",
    description: "Rib base thickness",
    requirement: "<= 70% of wall thickness",
    threshold: { max: 0.7 },
    unit: "x wall",
    severity: "warning",
    reasoning: "Thick ribs cause shrinkage porosity",
    fixSuggestion: "Reduce rib base to 60% of adjacent wall",
  },
  {
    id: "DC-005",
    name: "Cored Hole Diameter",
    process: "die_casting",
    category: "Holes",
    description: "Minimum diameter for cast-in holes",
    requirement: ">= 3mm diameter",
    threshold: { min: 3 },
    unit: "mm",
    severity: "warning",
    reasoning: "Small cores overheat and erode quickly",
    fixSuggestion: "Drill small holes after casting",
  },
  {
    id: "DC-006",
    name: "Cored Hole Depth",
    process: "die_casting",
    category: "Holes",
    description: "Maximum depth for blind cored holes",
    requirement: "Depth <= 4x diameter",
    threshold: { max: 4 },
    unit: "x diameter",
    severity: "warning",
    reasoning: "Deep cores deflect and cause core shifts",
    fixSuggestion: "Reduce depth or core from both sides",
  },
  {
    id: "DC-007",
    name: "Boss Design",
    process: "die_casting",
    category: "Bosses",
    description: "Bosses need adequate draft and fillets",
    requirement: "OD <= 2x ID, with 2 deg draft",
    threshold: { max: 2 },
    unit: "x ID",
    severity: "warning",
    reasoning: "Large bosses cause porosity and sink",
    fixSuggestion: "Use hollow bosses with gussets",
  },
  {
    id: "DC-008",
    name: "Slide Actions",
    process: "die_casting",
    category: "Mold",
    description: "External undercuts need side cores",
    requirement: "Minimize slide actions",
    threshold: {},
    unit: "count",
    severity: "critical",
    reasoning: "Each slide increases die cost significantly",
    fixSuggestion: "Redesign to eliminate undercuts where possible",
  },
  {
    id: "DC-009",
    name: "Machining Stock",
    process: "die_casting",
    category: "Tolerances",
    description: "Add stock for machined surfaces",
    requirement: "0.5-1mm stock on machined faces",
    threshold: { min: 0.5, recommended: 1 },
    unit: "mm",
    severity: "info",
    reasoning: "Cast surfaces have porosity in outer layer",
    fixSuggestion: "Add machining allowance to critical surfaces",
  },
  {
    id: "DC-010",
    name: "Parting Line Flash",
    process: "die_casting",
    category: "Mold",
    description: "Parting line location for flash trimming",
    requirement: "Parting line on edges for easy trimming",
    threshold: {},
    unit: "location",
    severity: "info",
    reasoning: "Die casting always produces flash at parting line",
    fixSuggestion: "Design parting line along trim-friendly edges",
  },
  {
    id: "DC-011",
    name: "Lettering",
    process: "die_casting",
    category: "Features",
    description: "Raised lettering is preferred",
    requirement: "Raised text >= 0.5mm high",
    threshold: { min: 0.5 },
    unit: "mm",
    severity: "info",
    reasoning: "Recessed text traps oxides and is harder to finish",
    fixSuggestion: "Use raised lettering with draft on sides",
  },
  {
    id: "DC-012",
    name: "Overflow Wells",
    process: "die_casting",
    category: "Mold",
    description: "Design accommodates overflow and vents",
    requirement: "Allow space for overflows in non-critical areas",
    threshold: {},
    unit: "location",
    severity: "info",
    reasoning: "Overflows capture first metal and trapped air",
    fixSuggestion: "Leave flat areas at end of fill for overflow attachment",
  },

  // ==========================================
  // 3D PRINTING FDM RULES (12 rules)
  // ==========================================

  {
    id: "3DP-001",
    name: "Minimum Wall Thickness",
    process: "3d_printing_fdm",
    category: "Walls",
    description: "Walls must be multiple of nozzle width",
    requirement: ">= 0.8mm (2x 0.4mm nozzle)",
    threshold: { min: 0.8, recommended: 1.2 },
    unit: "mm",
    severity: "critical",
    reasoning: "Thin walls dont print solidly",
    fixSuggestion: "Use wall thickness in multiples of nozzle diameter",
  },
  {
    id: "3DP-002",
    name: "Overhang Angle",
    process: "3d_printing_fdm",
    category: "Supports",
    description: "Maximum overhang without support",
    requirement: "<= 45 deg from vertical",
    threshold: { max: 45 },
    unit: "degrees",
    severity: "warning",
    reasoning: "Steep overhangs sag and have poor surface finish",
    fixSuggestion: "Redesign to self-supporting or orient part differently",
  },
  {
    id: "3DP-003",
    name: "Bridge Length",
    process: "3d_printing_fdm",
    category: "Features",
    description: "Maximum unsupported horizontal span",
    requirement: "<= 10mm without support",
    threshold: { max: 10, recommended: 5 },
    unit: "mm",
    severity: "warning",
    reasoning: "Long bridges sag in middle",
    fixSuggestion: "Add support structure or redesign",
  },
  {
    id: "3DP-004",
    name: "Hole Compensation",
    process: "3d_printing_fdm",
    category: "Holes",
    description: "Holes print smaller than designed",
    requirement: "Add 0.2-0.4mm to hole diameter",
    threshold: {},
    unit: "mm",
    severity: "info",
    reasoning: "Holes shrink due to filament squish",
    fixSuggestion: "Compensate hole diameter or drill/ream after printing",
  },
  {
    id: "3DP-005",
    name: "Minimum Feature Size",
    process: "3d_printing_fdm",
    category: "Features",
    description: "Smallest printable positive feature",
    requirement: ">= 0.8mm for detail",
    threshold: { min: 0.8 },
    unit: "mm",
    severity: "warning",
    reasoning: "Fine features may not resolve or break off",
    fixSuggestion: "Increase feature size or use SLA for fine detail",
  },
  {
    id: "3DP-006",
    name: "Layer Height",
    process: "3d_printing_fdm",
    category: "Finish",
    description: "Layer height affects strength and time",
    requirement: "0.1-0.3mm typical",
    threshold: { min: 0.1, max: 0.3 },
    unit: "mm",
    severity: "info",
    reasoning: "Thinner layers = better finish but longer print",
    fixSuggestion: "Use variable layer height where possible",
  },
  {
    id: "3DP-007",
    name: "Infill Percentage",
    process: "3d_printing_fdm",
    category: "Structure",
    description: "Internal fill density",
    requirement: "15-30% for most parts, 50%+ for structural",
    threshold: { min: 15, recommended: 20 },
    unit: "%",
    severity: "info",
    reasoning: "Higher infill = stronger but uses more material and time",
    fixSuggestion: "Use variable infill or design hollow with ribs",
  },
  {
    id: "3DP-008",
    name: "Part Orientation",
    process: "3d_printing_fdm",
    category: "Setup",
    description: "Z-axis is weakest direction",
    requirement: "Orient critical loads perpendicular to Z",
    threshold: {},
    unit: "orientation",
    severity: "critical",
    reasoning: "Layer adhesion is weakest bond",
    fixSuggestion: "Orient so loads are in XY plane",
  },
  {
    id: "3DP-009",
    name: "Support Access",
    process: "3d_printing_fdm",
    category: "Supports",
    description: "Supports must be removable",
    requirement: "Minimum 5mm access for support removal",
    threshold: { min: 5 },
    unit: "mm",
    severity: "warning",
    reasoning: "Trapped supports cannot be removed",
    fixSuggestion: "Ensure tool access to all support contact points",
  },
  {
    id: "3DP-010",
    name: "Thread Orientation",
    process: "3d_printing_fdm",
    category: "Features",
    description: "Threads should be oriented vertically",
    requirement: "Threads on Z-axis, minimum M6",
    threshold: { min: 6 },
    unit: "mm diameter",
    severity: "warning",
    reasoning: "Horizontal threads have poor engagement",
    fixSuggestion: "Use heat-set inserts for reliable threads",
  },
  {
    id: "3DP-011",
    name: "Snap-Fit Orientation",
    process: "3d_printing_fdm",
    category: "Features",
    description: "Snap arms need print orientation consideration",
    requirement: "Print snap arms flat or at angle",
    threshold: {},
    unit: "orientation",
    severity: "info",
    reasoning: "Layer lines affect snap arm strength",
    fixSuggestion: "Orient for layers along arm length",
  },
  {
    id: "3DP-012",
    name: "Assembly Clearance",
    process: "3d_printing_fdm",
    category: "Assembly",
    description: "Gap for press-fit or sliding parts",
    requirement: "0.2mm clearance for sliding, 0mm for press-fit",
    threshold: { min: 0.2 },
    unit: "mm",
    severity: "info",
    reasoning: "FDM parts are slightly oversized",
    fixSuggestion: "Test fit and adjust clearances",
  },

  // ==========================================
  // WELDMENT RULES (10 rules)
  // ==========================================

  {
    id: "WLD-001",
    name: "Weld Access",
    process: "weldment",
    category: "Access",
    description: "Welder must access joint",
    requirement: "Minimum 45 deg torch angle, 50mm clearance",
    threshold: { min: 50 },
    unit: "mm",
    severity: "critical",
    reasoning: "Inaccessible welds are incomplete or impossible",
    fixSuggestion: "Ensure clear line-of-sight to all weld joints",
  },
  {
    id: "WLD-002",
    name: "Joint Preparation",
    process: "weldment",
    category: "Joints",
    description: "Thick sections need edge prep",
    requirement: "Bevel/V-groove for material > 6mm",
    threshold: { min: 6 },
    unit: "mm",
    severity: "warning",
    reasoning: "Thick sections dont achieve full penetration",
    fixSuggestion: "Add appropriate bevel or groove preparation",
  },
  {
    id: "WLD-003",
    name: "Fit-up Gap",
    process: "weldment",
    category: "Joints",
    description: "Gap between parts before welding",
    requirement: "0-2mm for butt joints",
    threshold: { max: 2, recommended: 0 },
    unit: "mm",
    severity: "warning",
    reasoning: "Large gaps cause burn-through and excessive filler",
    fixSuggestion: "Improve fit-up or use backing bar",
  },
  {
    id: "WLD-004",
    name: "Fillet Weld Size",
    process: "weldment",
    category: "Welds",
    description: "Fillet leg size relative to material",
    requirement: "Leg = 70% of thinner member",
    threshold: { min: 0.7 },
    unit: "x thickness",
    severity: "info",
    reasoning: "Undersized welds are weak, oversized waste material",
    fixSuggestion: "Specify appropriate weld size on drawing",
  },
  {
    id: "WLD-005",
    name: "Distortion Control",
    process: "weldment",
    category: "Process",
    description: "Weld sequence to minimize warping",
    requirement: "Balance welds, work from center out",
    threshold: {},
    unit: "sequence",
    severity: "warning",
    reasoning: "Unbalanced welding causes significant distortion",
    fixSuggestion: "Design symmetric weldments, specify weld sequence",
  },
  {
    id: "WLD-006",
    name: "Material Thickness",
    process: "weldment",
    category: "Material",
    description: "Thin material burns through easily",
    requirement: ">= 1.5mm for MIG, >= 0.8mm for TIG",
    threshold: { min: 0.8 },
    unit: "mm",
    severity: "warning",
    reasoning: "Thin material overheats and burns through",
    fixSuggestion: "Use TIG for thin material or spot weld",
  },
  {
    id: "WLD-007",
    name: "Inspection Access",
    process: "weldment",
    category: "Inspection",
    description: "Critical welds must be visually inspectable",
    requirement: "Visual access to all structural welds",
    threshold: {},
    unit: "access",
    severity: "info",
    reasoning: "Hidden welds cannot be inspected for defects",
    fixSuggestion: "Design for weld visibility or specify NDT method",
  },
  {
    id: "WLD-008",
    name: "Material Compatibility",
    process: "weldment",
    category: "Material",
    description: "Dissimilar metals need special procedures",
    requirement: "Same alloy family preferred",
    threshold: {},
    unit: "compatibility",
    severity: "critical",
    reasoning: "Dissimilar metal welds can crack or corrode",
    fixSuggestion: "Use same material or mechanical fastening",
  },
  {
    id: "WLD-009",
    name: "Post-Weld Machining",
    process: "weldment",
    category: "Process",
    description: "Add stock for post-weld machining",
    requirement: "Minimum 3mm stock on machined surfaces",
    threshold: { min: 3 },
    unit: "mm",
    severity: "info",
    reasoning: "Welding distorts nearby surfaces",
    fixSuggestion: "Add machining allowance, stress relieve before machining",
  },
  {
    id: "WLD-010",
    name: "Weld Symbol Clarity",
    process: "weldment",
    category: "Documentation",
    description: "Weld symbols per AWS A2.4",
    requirement: "Complete weld symbol with size, type, length",
    threshold: {},
    unit: "documentation",
    severity: "info",
    reasoning: "Incomplete symbols cause fabrication errors",
    fixSuggestion: "Include all weld symbol elements per AWS A2.4",
  },

  // ==========================================
  // PCBA RULES (5 rules)
  // ==========================================

  {
    id: "PCB-001",
    name: "Trace Width for Current",
    process: "pcba",
    category: "Traces",
    description: "Trace width must handle expected current",
    requirement: "Per IPC-2221 calculator",
    threshold: {},
    unit: "mm/A",
    severity: "critical",
    reasoning: "Undersized traces overheat and fail",
    fixSuggestion: "Use IPC-2221 trace width calculator",
  },
  {
    id: "PCB-002",
    name: "Creepage Distance",
    process: "pcba",
    category: "Clearance",
    description: "Surface distance between conductors",
    requirement: "Per IPC-2221 for voltage level",
    threshold: {},
    unit: "mm",
    severity: "critical",
    reasoning: "Insufficient creepage causes arcing and fires",
    fixSuggestion: "Check creepage requirements for your voltage class",
  },
  {
    id: "PCB-003",
    name: "Clearance Distance",
    process: "pcba",
    category: "Clearance",
    description: "Air gap between conductors",
    requirement: "Per IPC-2221 for voltage level",
    threshold: {},
    unit: "mm",
    severity: "critical",
    reasoning: "Insufficient clearance causes arcing",
    fixSuggestion: "Check clearance requirements for your voltage class",
  },
  {
    id: "PCB-004",
    name: "Via Thermal Relief",
    process: "pcba",
    category: "Thermal",
    description: "Vias in ground planes need thermal relief",
    requirement: "Use thermal spokes for hand soldering",
    threshold: {},
    unit: "boolean",
    severity: "warning",
    reasoning: "Solid connections make hand soldering difficult",
    fixSuggestion: "Add thermal relief to vias in large copper pours",
  },
  {
    id: "PCB-005",
    name: "Component Spacing",
    process: "pcba",
    category: "Assembly",
    description: "Minimum spacing between components",
    requirement: ">= 0.5mm for SMD, >= 2mm for through-hole",
    threshold: { min: 0.5 },
    unit: "mm",
    severity: "warning",
    reasoning: "Tight spacing makes assembly and rework difficult",
    fixSuggestion: "Increase component spacing where possible",
  },
];

// Helper function to get rules by process
export function getRulesByProcess(process: ManufacturingProcess): DfmRule[] {
  return DFM_RULES.filter((rule) => rule.process === process);
}

// Helper function to get rule by ID
export function getRuleById(id: string): DfmRule | undefined {
  return DFM_RULES.find((rule) => rule.id === id);
}

// Get all unique categories for a process
export function getCategoriesByProcess(process: ManufacturingProcess): string[] {
  const rules = getRulesByProcess(process);
  return [...new Set(rules.map((r) => r.category))];
}

// Get rule count by process
export function getRuleCountByProcess(): Record<ManufacturingProcess, number> {
  const counts: Record<string, number> = {};
  for (const rule of DFM_RULES) {
    counts[rule.process] = (counts[rule.process] || 0) + 1;
  }
  return counts as Record<ManufacturingProcess, number>;
}
